/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Poppins"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        /* Vitals palette — Sotera Vital Intelligence */
        'vital-green':   '#00D97E',
        'vital-teal':    '#00DDA0',
        'vital-blue':    '#4DAAFF',
        'vital-red':     '#FF4B60',
        'vital-orange':  '#FF8C42',
        'vital-yellow':  '#F5C842',
        'vital-pink':    '#FF6B8A',
        'vital-purple':  '#9B77F5',
        /* Legacy aliases */
        'health-red':    '#FF4B60',
        'health-orange': '#FF8C42',
        'health-yellow': '#F5C842',
        'health-green':  '#00D97E',
        'health-teal':   '#00DDA0',
        'health-blue':   '#4DAAFF',
        'health-purple': '#9B77F5',
        'health-pink':   '#FF6B8A',
        'health-indigo': '#0D5A4E',
      },
      borderRadius: {
        sm:    '6px',
        md:    '10px',
        lg:    '14px',
        xl:    '18px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
      },
      boxShadow: {
        card:     '0 1px 4px rgba(0,0,0,0.60), 0 4px 16px rgba(0,0,0,0.35)',
        elevated: '0 8px 44px rgba(0,0,0,0.65)',
        glow:     '0 0 36px rgba(0,221,160,0.22), 0 0 80px rgba(0,221,160,0.08)',
        'glow-sm':'0 0 18px rgba(0,221,160,0.22)',
      },
      animation: {
        'orb-drift':       'orb-drift 26s ease-in-out infinite',
        'float':           'float 5.5s ease-in-out infinite',
        'glow-pulse':      'glow-pulse 3s ease-in-out infinite',
        'badge-ring':      'badge-ring 2.5s ease-in-out infinite',
        'fade-in':         'fade-in 0.4s ease both',
        'page-up':         'page-up 0.5s cubic-bezier(0.22,1,0.36,1) both',
        'portal-in':       'portal-in 0.55s cubic-bezier(0.22,1,0.36,1) both',
        'card-rise':       'card-rise 0.45s cubic-bezier(0.22,1,0.36,1) both',
        'shimmer':         'shimmer 1.7s ease-in-out infinite',
        'number-rise':     'number-rise 0.6s cubic-bezier(0.34,1.56,0.64,1) both',
        'ring-pulse-once': 'ring-pulse-once 1.4s cubic-bezier(0.22,1,0.36,1) both',
        'plasma-breathe':  'plasma-breathe 8s ease-in-out infinite',
        'live-ping':       'live-ping 1.8s cubic-bezier(0,0,0.2,1) infinite',
        'ai-border':       'ai-border-breathe 2s ease-in-out infinite',
        'ai-cursor':       'ai-cursor 0.85s step-end infinite',
        'ghost-rise':      'ghost-rise 0.7s cubic-bezier(0.34,1.56,0.64,1) both',
      },
      fontSize: {
        'display':        ['52px', { lineHeight: '1.08', letterSpacing: '-3px',  fontWeight: '800' }],
        'hero':           ['36px', { lineHeight: '1.1',  letterSpacing: '-1.8px', fontWeight: '800' }],
        'metric-display': ['80px', { lineHeight: '1',    letterSpacing: '-5px',   fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}
