"""initial schema

Revision ID: 271af67e5d33
Revises: 
Create Date: 2026-05-12 21:01:48.335717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271af67e5d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertes', schema=None) as batch_op:
        batch_op.alter_column('vue',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE = le patient a vu cette alerte (badge vidé)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('idx_alertes_patient_vue'))
        batch_op.drop_table_comment(
        existing_comment='Alertes de santé (seuils, tendances, corrélations)'
    )

    with op.batch_alter_table('annotations_medecin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_annotations_mesure'))
        batch_op.drop_table_comment(
        existing_comment='Annotations médicales sur une mesure spécifique (visible patient)'
    )

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='redige | valide | archive',
               existing_nullable=False,
               existing_server_default=sa.text("'redige'::character varying"))
        batch_op.drop_index(batch_op.f('idx_consultations_patient_date'))
        batch_op.drop_table_comment(
        existing_comment='Comptes-rendus des consultations médicales'
    )

    with op.batch_alter_table('conversations_ia', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID — identifie une session de conversation',
               existing_nullable=False)
        batch_op.alter_column('ordre_dans_session',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ordre chronologique dans la session (0, 1, 2…)',
               existing_nullable=False)
        batch_op.alter_column('anonymise',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="TRUE = données anonymisées (conformité RGPD — droit à l'oubli)",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('idx_ia_patient_session'))
        batch_op.drop_index(batch_op.f('idx_ia_session_ordre'))
        batch_op.drop_table_comment(
        existing_comment="Historique des conversations avec l'assistant IA (Claude)"
    )

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="UUID — regroupe tous les messages d'un même fil",
               existing_nullable=False)
        batch_op.alter_column('supprime_par_expediteur',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete côté expéditeur — message masqué, non effacé',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('supprime_par_destinataire',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete côté destinataire — message masqué, non effacé',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('idx_messages_conversation_date'))
        batch_op.drop_index(batch_op.f('idx_messages_destinataire_non_lus'))
        batch_op.drop_table_comment(
        existing_comment='Messages échangés entre patient et médecin'
    )

    with op.batch_alter_table('mesures', schema=None) as batch_op:
        batch_op.alter_column('valeur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valeur principale (ex. systolique pour la tension, poids, glycémie…)',
               existing_nullable=False)
        batch_op.alter_column('contexte',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NULL = non renseigné | a_jeun | post_repas | au_repos | apres_effort | avant_coucher',
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='saisie (manuelle) | import_csv | api (wearable…)',
               existing_nullable=True,
               existing_server_default=sa.text("'saisie'::character varying"))
        batch_op.drop_index(batch_op.f('idx_mesures_patient_date'))
        batch_op.drop_index(batch_op.f('idx_mesures_type'))
        batch_op.drop_table_comment(
        existing_comment='Mesure principale de santé saisie par le patient'
    )

    with op.batch_alter_table('mesures_composantes', schema=None) as batch_op:
        batch_op.alter_column('composante',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nom libre de la composante — ex. diastolique, HDL, LDL',
               existing_nullable=False)
        batch_op.alter_column('valeur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valeur numérique de la composante',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_composantes_mesure'))
        batch_op.drop_table_comment(
        existing_comment="Valeurs secondaires d'une mesure (diastolique, HDL, LDL…)"
    )

    with op.batch_alter_table('preferences_utilisateur', schema=None) as batch_op:
        batch_op.alter_column('cle',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Ex. canal_alerte, langue, vitascore_visible, dashboard_compact',
               existing_nullable=False)
        batch_op.alter_column('valeur',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Valeur texte libre — parser côté applicatif selon la clé',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_prefs_user'))
        batch_op.drop_table_comment(
        existing_comment='Préférences utilisateur (notifications, affichage…) — modèle clé/valeur'
    )

    with op.batch_alter_table('relations_medecin_patient', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='FALSE = relation terminée (date_fin renseignée)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('idx_rel_medecin_active'))
        batch_op.drop_index(batch_op.f('idx_rel_patient_active'))
        batch_op.drop_table_comment(
        existing_comment='Quels médecins suivent quels patients'
    )

    with op.batch_alter_table('types_mesure', schema=None) as batch_op:
        batch_op.alter_column('seuil_min_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Borne basse zone normale (OMS)',
               existing_nullable=True)
        batch_op.alter_column('seuil_max_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Borne haute zone normale (OMS)',
               existing_nullable=True)
        batch_op.alter_column('seuil_danger_bas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Borne basse zone danger — déclenche alerte rouge',
               existing_nullable=True)
        batch_op.alter_column('seuil_danger_haut',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Borne haute zone danger — déclenche alerte rouge',
               existing_nullable=True)
        batch_op.alter_column('ponderation_vitascore',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Poids de cet indicateur dans le VitaScore (0 à 1)',
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
        batch_op.drop_table_comment(
        existing_comment="Types d'indicateurs (poids, tension, glycémie…) avec seuils OMS"
    )

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe_hash',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='Hash bcrypt — jamais le mot de passe en clair',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='patient | medecin',
               existing_nullable=False,
               existing_server_default=sa.text("'patient'::character varying"))
        batch_op.alter_column('taille_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Pour calcul IMC, en centimètres',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_utilisateurs_email'))
        batch_op.drop_table_comment(
        existing_comment='Comptes patients et médecins'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Comptes patients et médecins',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_utilisateurs_email'), ['email'], unique=False)
        batch_op.alter_column('taille_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Pour calcul IMC, en centimètres',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               comment='patient | medecin',
               existing_nullable=False,
               existing_server_default=sa.text("'patient'::character varying"))
        batch_op.alter_column('mot_de_passe_hash',
               existing_type=sa.VARCHAR(length=256),
               comment='Hash bcrypt — jamais le mot de passe en clair',
               existing_nullable=False)

    with op.batch_alter_table('types_mesure', schema=None) as batch_op:
        batch_op.create_table_comment(
        "Types d'indicateurs (poids, tension, glycémie…) avec seuils OMS",
        existing_comment=None
    )
        batch_op.alter_column('ponderation_vitascore',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Poids de cet indicateur dans le VitaScore (0 à 1)',
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('seuil_danger_haut',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Borne haute zone danger — déclenche alerte rouge',
               existing_nullable=True)
        batch_op.alter_column('seuil_danger_bas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Borne basse zone danger — déclenche alerte rouge',
               existing_nullable=True)
        batch_op.alter_column('seuil_max_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Borne haute zone normale (OMS)',
               existing_nullable=True)
        batch_op.alter_column('seuil_min_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Borne basse zone normale (OMS)',
               existing_nullable=True)

    with op.batch_alter_table('relations_medecin_patient', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Quels médecins suivent quels patients',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_rel_patient_active'), ['patient_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('idx_rel_medecin_active'), ['medecin_id', 'active'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               comment='FALSE = relation terminée (date_fin renseignée)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('preferences_utilisateur', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Préférences utilisateur (notifications, affichage…) — modèle clé/valeur',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_prefs_user'), ['user_id'], unique=False)
        batch_op.alter_column('valeur',
               existing_type=sa.TEXT(),
               comment='Valeur texte libre — parser côté applicatif selon la clé',
               existing_nullable=False)
        batch_op.alter_column('cle',
               existing_type=sa.VARCHAR(length=100),
               comment='Ex. canal_alerte, langue, vitascore_visible, dashboard_compact',
               existing_nullable=False)

    with op.batch_alter_table('mesures_composantes', schema=None) as batch_op:
        batch_op.create_table_comment(
        "Valeurs secondaires d'une mesure (diastolique, HDL, LDL…)",
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_composantes_mesure'), ['mesure_id'], unique=False)
        batch_op.alter_column('valeur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valeur numérique de la composante',
               existing_nullable=False)
        batch_op.alter_column('composante',
               existing_type=sa.VARCHAR(length=50),
               comment='Nom libre de la composante — ex. diastolique, HDL, LDL',
               existing_nullable=False)

    with op.batch_alter_table('mesures', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Mesure principale de santé saisie par le patient',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_mesures_type'), ['type_mesure_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_mesures_patient_date'), ['patient_id', sa.literal_column('date_mesure DESC')], unique=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               comment='saisie (manuelle) | import_csv | api (wearable…)',
               existing_nullable=True,
               existing_server_default=sa.text("'saisie'::character varying"))
        batch_op.alter_column('contexte',
               existing_type=sa.VARCHAR(length=50),
               comment='NULL = non renseigné | a_jeun | post_repas | au_repos | apres_effort | avant_coucher',
               existing_nullable=True)
        batch_op.alter_column('valeur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valeur principale (ex. systolique pour la tension, poids, glycémie…)',
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Messages échangés entre patient et médecin',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_messages_destinataire_non_lus'), ['destinataire_id', 'lu', 'envoye_le'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_conversation_date'), ['conversation_id', 'envoye_le'], unique=False)
        batch_op.alter_column('supprime_par_destinataire',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete côté destinataire — message masqué, non effacé',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('supprime_par_expediteur',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete côté expéditeur — message masqué, non effacé',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('conversation_id',
               existing_type=sa.UUID(),
               comment="UUID — regroupe tous les messages d'un même fil",
               existing_nullable=False)

    with op.batch_alter_table('conversations_ia', schema=None) as batch_op:
        batch_op.create_table_comment(
        "Historique des conversations avec l'assistant IA (Claude)",
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_ia_session_ordre'), ['session_id', 'ordre_dans_session'], unique=False)
        batch_op.create_index(batch_op.f('idx_ia_patient_session'), ['patient_id', 'session_id', sa.literal_column('date_message DESC')], unique=False)
        batch_op.alter_column('anonymise',
               existing_type=sa.BOOLEAN(),
               comment="TRUE = données anonymisées (conformité RGPD — droit à l'oubli)",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ordre_dans_session',
               existing_type=sa.INTEGER(),
               comment='Ordre chronologique dans la session (0, 1, 2…)',
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               comment='UUID — identifie une session de conversation',
               existing_nullable=False)

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Comptes-rendus des consultations médicales',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_consultations_patient_date'), ['patient_id', sa.literal_column('date_consultation DESC')], unique=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=30),
               comment='redige | valide | archive',
               existing_nullable=False,
               existing_server_default=sa.text("'redige'::character varying"))

    with op.batch_alter_table('annotations_medecin', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Annotations médicales sur une mesure spécifique (visible patient)',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_annotations_mesure'), ['mesure_id'], unique=False)

    with op.batch_alter_table('alertes', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Alertes de santé (seuils, tendances, corrélations)',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_alertes_patient_vue'), ['patient_id', 'vue'], unique=False)
        batch_op.alter_column('vue',
               existing_type=sa.BOOLEAN(),
               comment='TRUE = le patient a vu cette alerte (badge vidé)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
