"""initial schema

Revision ID: cc2954a7b13a
Revises: a1b2c3d4e5f6
Create Date: 2026-05-12 23:00:15.045780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2954a7b13a'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sessions_ia_patient'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sessions_ia_patient'), ['patient_id', 'updated_at'], unique=False)

    # ### end Alembic commands ###
